link:
  spj_dev: https://demo.automationtesting.in/Register.html

login:
  perfil_adm: 236046275
  delegado_capital: 397045694
  escrivao_capital: 496034546
  delegado_interior: 462044804
  psw: Teste@123

link_API:
  url_api:  https://www.4devs.com.br/ferramentas_online.php